#server:
#  port: 5002
server:
  port: 8082
spring:
  application:
    name: salon

  datasource:
    url: jdbc:oracle:thin:@tlz3t5ba8btq7pbd_high?TNS_ADMIN=src/main/resources/Wallet_TLZ3T5BA8BTQ7PBD
    username: ADMIN2
    password: Admin1234567  # Corregir si hay diferencia con ADMIN2x
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
        id:
          new_generator_mappings: true



  mail:
    host: smtp.gmail.com
    port: 587
    username: gedelashipa.1321@gmail.com
    password: rlxz dggl spmd byfd
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: read-only
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "USER"
    description: "USER API For Salon Booking System"
    version: "1.0.0"